#server:
#  port: 12000
#  servlet:
#    session:
#      timeout: 30m
#
#spring:
#  application:
#    name: tmeshmall-search
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        # 应用开启端口，接收dashboard限流规则，如果被占用会默认+1
#        port: 28719
#        #配置sentinel dashboard地址
#        dashboard: 127.0.0.1:28080
#  zipkin:
#    # zipkin服务器的地址
#    base-url: http://127.0.0.1:9411/
#    # 关闭服务发现，否则Springcloud会把zipkin当做服务名称
#    discovery-client-enabled: false
#    # 数据传输方式
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      rate: 1 # 设置抽样采集率 默认为0.1
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password: tmesh729
#  thymeleaf:
#    cache: false
#  session:
#    store-type: redis
#
## 开启feign熔断，开启后能够监控到远程调用资源
#feign:
#  sentinel:
#    enabled: true
#
## 开启日志
#logging:
#  group:
#    tomcat: org.apache.catalina,org.apache.coyote,org.apache.tomcat
#  level:
##    com.baomidou.example.mapper: debug
#    com.tmesh.tmeshmall: debug
#    org.springframework: debug
#    # feign调用日志，链路日志
#    org.springframework.cloud.openfeign: debug
#    org.springframework.cloud.sleuth: debug
#    root: debug
#    sql: debug
#    tomcat: info
#    web: info
#  file:
#    name: ./tmeshmall-logs/search.log

##暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
